#!/bin/bash

# Check that we don't get debug symbols [#@] on some test texts.

set -e -u

cd "$(dirname "$0")"


out=$(mktemp -t hash-count-swe-nor.XXXXXXXXXX)
trap 'rm -f "${out}"' EXIT

# TODO: regressions:
# swe-nno nob-swe
for dir in swe-nob nno-swe; do
    src=${dir%%-*}

    # cat ../texts/*."${src}".txt | apertium -f html-noent -d .. "${dir}"-dgen > "${out}"
    # TODO: -f html-noent does rehtml or something turning dgen tags into &lt;&gt;
    cat ../texts/*."${src}".txt | apertium-deshtml | apertium -f none -d .. "${dir}"-dgen > "${out}"

    current=$(grep -c '[#@]' "${out}" || true)

    if [[ "${current}" -gt 0 ]]; then
        echo "ERROR: texts/*.${src}.txt translated through ${dir} gave debug sybols [#@]:"
        grep -n '[#@]' "${out}"
        exit 1
    fi
done
